[package]
name = "javy"
version = "0.1.0"
authors = ["Saúl Cabrera <saulecabrera@gmail.com>"]
edition = "2018"
build = "build.rs"

[[bin]]
name = "javy"

[dependencies]
wizer = { git = "https://github.com/bytecodealliance/wizer", branch = "main" }
which = "4.2"
structopt = "0.3"
anyhow = "1.0"
tempfile = "3.2.0"
binaryen = "0.12.0"

[dev-dependencies]
wasmtime = { version = "0.29", features = ["async"] }
wasmtime-wasi = { version = "0.29", features = ["tokio"] }
wasi-common = { version = "0.29" }
async-trait = "0.1"
tokio = { version = "1.10", features = ["full"] }
rmp-serde = "0.15"
uuid = { version = "0.8", features = ["v4"] }
lazy_static = "1.4"
serde = { version = "1.0", default-features = false, features = ["derive"] }

