[package]
name = "javy"
version = "0.1.0"
authors = ["Saúl Cabrera <saulecabrera@gmail.com>"]
edition = "2018"
build = "build.rs"

[[bin]]
name = "javy"

[dev-dependencies]
wasmtime = "0.29.0"
wasmtime-wasi = "0.29.0"
serde = "1.0.126"
serde_json = "1.0.64"
rmp-serde = "0.15.5"
rmpv = {version = "0.4.7", features = ["with-serde"]}
proptest = "1"

[dependencies]
wizer = { git = "https://github.com/bytecodealliance/wizer", branch = "main" }
which = "4.2"
structopt = "0.3"
anyhow = "1.0"
tempfile = "3.2.0"

[build-dependencies]
which = "4.2"

