[package]
name = "javy"
version = "0.4.0"
authors = ["Saúl Cabrera <saulecabrera@gmail.com>"]
edition = "2018"
build = "build.rs"

[[bin]]
name = "javy"

[dependencies]
which = "4.2"
structopt = "0.3"
anyhow = "1.0"
tempfile = "3.2.0"
tera = "1.15"
wat = "1.0.36"

[dev-dependencies]
wasmtime = "0.34.2"
wasmtime-wasi = "0.34.2"
wasi-common = "0.34.2"
serde_json = "1.0"
uuid = { version = "0.8", features = ["v4"] }
lazy_static = "1.4"
serde = { version = "1.0", default-features = false, features = ["derive"] }

[build-dependencies]
wizer = { git = "https://github.com/bytecodealliance/wizer", branch = "main" }
anyhow = "1.0"
binaryen = "0.12.0"