[package]
name = "javy"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
build = "build.rs"

[[bin]]
name = "javy"

[dependencies]
which = "4.2"
structopt = "0.3"
anyhow = { workspace = true }
tempfile = "3.2.0"
tera = "1.15"
wat = "1.0.36"
base64 = "0.13.0"

[dev-dependencies]
wasmtime = { workspace = true }
wasmtime-wasi = { workspace = true }
wasi-common = { workspace = true }
serde_json = "1.0"
uuid = { version = "0.8", features = ["v4"] }
lazy_static = "1.4"
serde = { version = "1.0", default-features = false, features = ["derive"] }
criterion = "0.3"
num-format = "0.4.3"

[build-dependencies]
wizer = { git = "https://github.com/bytecodealliance/wizer", branch = "main" }
anyhow = "1.0"
binaryen = "0.12.0"

[[bench]]
name = "benchmark"
harness = false
