[package]
name = "javy-core"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = { workspace = true }
base64 = "0.13.0"
quickjs-wasm-rs = { path = "../quickjs-wasm-rs", features = ["json"] }
wee_alloc = "0.4.5"
once_cell = { workspace = true }
