[package]
name = "javy-core"
version = "0.3.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = { workspace = true }
quickjs-wasm-rs = { path = "../quickjs-wasm-rs", features = ["json"] }
wee_alloc = "0.4.5"
once_cell = { workspace = true }
