[package]
name = "javy-core"
version = "0.3.0"
authors = ["Saúl Cabrera <saulecabrera@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0"
quickjs-wasm-rs = { path = "../quickjs-wasm-rs", features = ["json"] }
wee_alloc = "0.4.5"
once_cell = "1.4.0"
