[package]
name = "javy-core"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
base64 = "0.13.0"
anyhow = { workspace = true }
quickjs-wasm-rs = { path = "../quickjs-wasm-rs" }
once_cell = { workspace = true }
