[package]
name = "javy2"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow = { workspace = true }
quickjs-wasm-rs = { path = "../quickjs-wasm-rs" }
